-- Just reference.

CREATE TABLE QUESTIONS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_time TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    view_cnt BIGINT NOT NULL
);

CREATE TABLE ANSWERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    question_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_time TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY (question_id) REFERENCES QUESTIONS(id) ON DELETE CASCADE
);

CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    pw VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE QUESTION_VOTERS (
    question_id BIGINT,
    voter_id BIGINT,
    PRIMARY KEY (question_id, voter_id),
    FOREIGN KEY (question_id) REFERENCES QUESTIONS(id) ON DELETE CASCADE
);

CREATE TABLE ANSWER_VOTERS (
    answer_id BIGINT,
    voter_id BIGINT,
    PRIMARY KEY (answer_id, voter_id),
    FOREIGN KEY (answer_id) REFERENCES ANSWERS(id) ON DELETE CASCADE
);

CREATE TABLE CATEGORIES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255) NOT NULL
);